examples/MilvusClientExample.go
The index type is IVFFLAT
https://github.com/milvus-io/milvus-sdk-go/blob/66d03376e34a8ac0e4bda898c2f82350f06b3918/examples/MilvusClientExample.go#L207
But the comment is IVFSQ8
https://github.com/milvus-io/milvus-sdk-go/blob/66d03376e34a8ac0e4bda898c2f82350f06b3918/examples/MilvusClientExample.go#L243
=> Fix a comment

examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go, milvus/MilvusGrpcClient.go
1. Remove redundant code in `MilvusClientExample.go`
2. Use `go fmt` to format the code
=> Remove redundant code

client/client.go, client/client_grpc_collection.go
Hide `Connect` from Client interface
Connect behavior shall be invoked int `NewXXXClient` method. Thus different connection options can be explicitly specified.
Fix issue: #172 
=> Hide Connect method

docs/create_collection.md
This works on the issue #191  
Added the schema structure in a table in  the create_collection.md in the docs
Describes the various fields of the schema required and type of each field
=> add schema table for collection creation in docs

client/client_grpc_data.go
Thanks for @xiaocai2333 
Signed-off-by: Letian Jiang <letian.jiang@zilliz.com>
=> Fix timestamp bug

README.md
fixed #316
When calling `client.NewGrpcClient`, if an error is returned, the client is nil. 
Need to call `client.Close` after processing the error.
=> fix readme to current example

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/main_test.go, test/testcases/search_test.go
- Add collection search cases
issue: #215 
=> Add collection search cases

entity/bulkinsert.go
related:#393
Signed-off-by: wayblink <anyang.wang@zilliz.com>
=> Support get bulk insert progress

test/testcases/main_test.go
- Remove test teardown clear all collections
In order not to drop their collections when running with other types of tests
=> Remove test teardown clear all collections

client/client.go, client/client_grpc_collection.go, client/client_grpc_collection_test.go
=> Add RenameCollection API

entity/columns.go, entity/columns_test.go
See also https://github.com/milvus-io/milvus/issues/23850
=> Handle LongData returned when queryresult is empty

client/client_mock_test.go, client/data.go, client/data_test.go, client/insert.go, client/insert_test.go, client/row_test.go, entity/columns.go, entity/columns_json.go, entity/columns_json_test.go, entity/rows.go, entity/rows_test.go, entity/schema.go, entity/schema_test.go, go.mod, go.sum
=> Support anonymous dynamic schema

entity/rows.go, entity/rows_test.go, examples/dynamic_schema/dynamic_schema.go
=> Support row interface with map[string]any

client/collection.go, client/options.go, client/options_test.go
See also milvus-io/milvus#24402
=> Add Logical partition num options for create collection

client/collection.go
Use `grpc.DialContext` in `client.NewClient`.
Allow user to determine the cancelation or timeout of connect operation.
=> [Enhancement] use grpc.DialContext in client.NewClient

client/data.go, client/grpc_client.go, client/index.go, entity/index.go, entity/index_scalar.go, examples/index/index.go, test/testcases/index_test.go
For Scalar index support:
- Add `scalarIndex` type
- Remove field type check for most index usage
- Fix index example code
- Fix connect logic error
See also #497
=> Support scalar index

client/insert.go, client/insert_test.go, entity/columns.go, entity/schema.go, entity/schema_test.go
Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
https://github.com/milvus-io/milvus/issues/23337
=> Support default value

client/client.go, client/config.go, client/rate_limit_interceptor.go, client/rate_limit_interceptor_test.go, client/results.go
See also milvus-io/milvus#25693
=> Make retry on ratelimit configurable

client/options.go, test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/connect_test.go, test/testcases/database_test.go, test/testcases/delete_test.go, test/testcases/main_test.go, test/testcases/resource_group_test.go
=> [cherry-pick]Add cases about resource group and database

.github/workflows/nightly_ci.yml, ci/milvus-operator/milvus-nightly.yaml
=> Configure schedule nightly for branch v2.2.x

client/data.go, client/maintainance.go, client/maintainance_test.go, client/options.go
issue: https://github.com/milvus-io/milvus/issues/26070
=> Remove time travel

ci/milvus-operator/milvus-nightly.yaml, test/testcases/resource_group_test.go
- Update L3 cases
- update nightly qn replicas from 1 to 4
=> Update L3 cases and nightly qn replicas

entity/index.go
=> Remove empty index type param

client/client.go, client/insert.go, client/options.go
=> Update to support milvus-backup

client/index.go
=> Remove a outdated comment

client/data.go
Fix #584
/kind bug
This PR let output result set only check extra fields 
If Milvus server returns more column than output fields specified, just return them
=> Fix outputFields logic conflicted between aggr & dynamic schema

client/insert.go, client/row.go
=> Remove default partition name logic from `InsertRows` and `Upsert`

.github/workflows/main.yml, .github/workflows/test-ci.yaml, README.md, common/common.go, go.mod, go.sum
=> Bump version to v2.3.1

test/testcases/index_test.go, test/testcases/load_release_test.go
=> Fix e2e case error message due to milvus change

entity/genidx/genidx.go, entity/indexes_gen.go, entity/indexes_gen_test.go, entity/indexes_search_param_gen.go
=> Fix SCANN index type used ivf_flat value

client/index.go, client/index_test.go
See also #594 
sync behavior with pymilvus
=> Remove `Flush` operation before create index

client/data.go, client/data_test.go, test/testcases/search_test.go
=> Add wildcard outputfield expansion logic back

client/admin.go, client/admin_test.go, client/client.go, entity/check_health.go
=> impl check health

client/data_test.go, entity/columns.go
=> Fix unsafe direct field access for Int8/Int16 result data

client/insert.go
Previously go sdk removed field check for insert but same logic remains in `Upsert` method
See also #613
/kind bug
=> Remove field check logic for upsert

test/common/utils.go, test/testcases/insert_test.go, test/testcases/main_test.go, test/testcases/option.go, test/testcases/query_test.go, test/testcases/upsert_test.go
- Add upsert test cases
- Add prepare collection fun for case
=> Add upsert test cases

test/testcases/upsert_test.go
=> Fix `TestUpsertInvalidColumnData` case using dynamic schema

client/data.go, test/testcases/upsert_test.go
=> Fix QueryByPKs composes wrong expr when pk data has spaces

client/data.go
Since empty field data has no info for field name nor field type 
it's more meaningful to skip parse field data for empty resultSet
This PR adds ResultCount check before performing fieldData parsing
When resultSet is empty, the entry shall have no error with empty fields
See also #623
=> Parse result field data when result set entry count is not zero

test/common/response_check.go, test/common/utils.go, test/common/utils_client.go, test/testcases/collection_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/main_test.go, test/testcases/option.go, test/testcases/partition_key_test.go, test/testcases/query_test.go, test/testcases/search_test.go, test/testcases/upsert_test.go
- Add array test cases
- Add some array column or rows data util generation func
- Optimize row data generation
=> Add array field type test cases

client/client.go, client/client_mock_test.go, client/collection.go, client/collection_test.go, client/data_test.go, client/database.go, client/database_test.go, client/index.go, client/index_test.go, client/insert.go, client/mq_message.go, client/mq_message_test.go, client/options.go, client/options_msg_base.go, client/partition.go, client/partition_test.go, entity/mq_message.go, go.sum, mocks/MilvusServiceServer.go
=> Support the replicate message api

client/collection.go, common/common.go, go.mod, go.sum, test/testcases/query_test.go, test/testcases/search_test.go
Bump proto version to v2.3.3 and change go sdk verison
Also make create collection enable dynamic schema work
=> Bump version & make Collection Option EnableDynamicSchema work

entity/collection_attr.go
- Add `entity.Mmap(enabled bool)` for enabling mmap
=> feat: support enabling mmap for collection

entity/collection_attr.go
This reverts commit 83f95d7ff26131c37e8ac7daf4a63013549b40cf.
=> Revert "feat: support enabling mmap for collection (#632)"

test/testcases/collection_test.go, test/testcases/highlevel_test.go, test/testcases/index_test.go, test/testcases/search_test.go
update case due to default index name change
=> test:update case due to default index name change

client/client_mock_test.go, common/common.go, go.mod, go.sum, merr/errors.go, merr/errors_test.go, merr/utils.go, mocks/MilvusServiceServer.go
This PR:
- Bump version to 2.4.0-dev
- Add merr package, which is simplified version from milvus main repo
- Add mock API due to proto update
=> Add merr package to utilize milvus error

client/client_mock_test.go, client/index.go, go.mod, go.sum
support to enable/disable index mmap mode by altering index
=> feat: support alter index

.github/workflows/main.yml, merr/errors.go, merr/errors_test.go, merr/utils.go
This PR:
- Add merr package, which is simplified version from milvus main repo
- Add mock API due to proto update
---------
=> enhance: [Cherry-pick] Add merr package to utilize milvus error (#645)

entity/schema.go, entity/schema_test.go, test/testcases/collection_test.go
cherry pick from master
pr: #655 
Resolves: #654
=> fix: [Cherry-pick] deduce AutoID from field info

common/common.go, go.mod, go.sum
=> enhance: Bump SDK & proto version to v2.3.5

entity/index.go, entity/index_cagra.go, entity/index_test.go
See also milvus-io/milvus#29230
=> enhance: Suport GPUCagra & GPUBruteForce index type

client/ann_request.go, client/client.go, client/client_test.go, client/data.go, client/reranker.go, examples/multivectors/main.go
See also: milvus-io/milvus#25639
milvus pr:  milvus-io/milvus#29433
=> enhance: Support hybrid search multiple vector fields

test/common/utils.go, test/testcases/collection_test.go, test/testcases/gorupby_search_test.go, test/testcases/index_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- add test cases for groupby search
- update case: different metrics type for BinFlat and BinIvfFlat index
- update case: create scalar index for all kinds of supported FieldType
- update case: json support multiple forms
- add case: change of vector's legal dim
- add case: search from growing segments
see also: #670
=> Add test cases for groupby search

client/data.go, client/util.go, client/util_test.go, merr/errors.go, test/testcases/search_test.go
1. Support retry on milvus errors.
2. Retry on ErrInconsistentRequery for search and hybrid search operations.
issue: https://github.com/milvus-io/milvus/issues/29656
related milvus pr: https://github.com/milvus-io/milvus/pull/31343
=> fix: Support retry on milvus errors and retry on ErrInconsistentRequery

test/testcases/groupby_search_test.go
`TestSearchGroupByFloatDefault` may fail randomly since hitrate maybe lower than 0.2, which is reasonable due to index variable.
=> fix: Skip `TestSearchGroupByFloatDefault` case

client/client_mock_test.go, go.mod, go.sum, mocks/MilvusServiceServer.go
Sync proto version to v2.4.0-rc.1 to support new features
=> enhance: Bump milvus-proto/go-api to v2.4.0-rc.1

client/reranker.go
Use correct rerankType in WeightedRerank params
=> fix: Rectify Weighted Rerank params

client/insert.go, entity/columns.go, entity/columns_sparse.go, entity/columns_sparse_test.go, entity/schema.go
See also milvus-io/milvus#29419
=> enhance: Support Sparse Embedding

entity/genidx/genidx.go, entity/indexes_search_param_gen.go, entity/indexes_search_param_gen_test.go
only make sure level > 0, do not check range, range check should be done in the server side
=> Update autoindex level check

client/insert.go
This place holder type was set to FloatVector by mistake. This PR rectify the value for fp16 vector.
=> fix: Use corrent place holder type for fp16 vector

client/index.go
=> fix: Filter index info base on provided field name

examples/multivectors/main.go, test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/compact_test.go, test/testcases/delete_test.go, test/testcases/groupby_search_test.go, test/testcases/hybrid_search_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go, test/testcases/option.go, test/testcases/partition_key_test.go, test/testcases/query_test.go, test/testcases/search_test.go, test/testcases/upsert_test.go
- Add test cases for f616 and bf16 vector type
- Add test cases for multi-vectors and hybrid search
=> Add test cases for fp16, bf16, hybrid search

test/common/utils.go, test/testcases/delete_test.go, test/testcases/index_test.go, test/testcases/query_test.go, test/testcases/resource_group_test.go
HNSW support on binary vector field is not supported. Change case behavior and skip some cases due to previously reported bug.
=> fix: Build binary index on binary field and skip some cases

entity/index_scalar.go, entity/index_scalar_test.go
=> fix: Pass index type for Scalar indexes

test/common/response_check.go, test/testcases/hybrid_search_test.go, test/testcases/search_test.go
- nq = 1 case fails due to milvus beavior change
- check error not nil before check msg
=> Fix hybrid search case and response check

client/index.go
=> fix: Pass extra params when creating Index

client/client.go
`AlterIndex` has already been implemented but not exported in client interface.
=> enhance: Export `AlterIndex` API in client interface

entity/columns_sparse.go, entity/index.go, entity/index_sparse.go, entity/index_sparse_test.go
See also #708
Support SparseInverted & SparseWAND
=> enhance: Add Sparse Index type enum

client/ann_request.go, client/client.go, client/data.go
=> enhance: Support offset in hybrid search outer request

entity/columns_sparse.go
=> fix: Use correct idx when Serialize Sparse vector

test/testcases/delete_test.go, test/testcases/search_test.go
- Sparse Vector support range search
- Error message update
- Remove range filter to make case work
=> fix: Fix recent behavior change caused case failure

client/data.go, client/reranker.go, test/base/milvus_client.go, test/common/utils.go, test/testcases/hybrid_search_test.go
See also milvus-io/milvus#32562
=> fix: Pass offset param in rerank params for HybridSearch

client/client.go, client/rbac.go, client/rbac_test.go, entity/rbac.go
resolves: #698
I've added an entity:
```
type UserDescription struct {
Name  string
Roles []string
}
```
And two methods and tests for them:
- `DescribeUser(ctx context.Context, username string) (entity.UserDescription, error)` - which returns UserDescription for a specific user.
- `DescribeUsers(ctx context.Context) ([]entity.UserDescription, error)` - which returns UserDescription for all users presented. 
The thing that I want to raise is that I am not sure if it is feasible to return empty `UserDescription` entity in case the user from `DescribeUser` method doesn't exist, I would highly appreciate suggestions here.
Also, I am not much familiar with the `milvus-sdk-go` codebase and this is my first PR here, so any comments/feedback/suggestions would be highly appreciated, thanks!
=> enhance: Add Describe User methods

client/config.go
=> fix: Make custom DialOption overwrite default ones

test/common/utils.go
See also milvus-io/milvus#32950
Default partition number is updated to 16 which caused some case failed
=> fix: Sync default partition number to 16

client/ann_request.go, client/data.go
When group by is not set, make sdk not passing empty GroupByField search param.
=> enhance: Not pass empty group by field search param

client/client.go, client/rbac.go, client/rbac_test.go, entity/rbac.go
Resolves #744
Two methods:
```
// ListGrant lists a grant info for the role and the specific object
ListGrant(ctx context.Context, role string, object string, objectName string, dbName string) ([]entity.RoleGrants, error)
// ListGrants lists all assigned privileges and objects for the role.
ListGrants(ctx context.Context, role string, dbName string) ([]entity.RoleGrants, error)
```
And a structure:
```
type RoleGrants struct {
Object        string
ObjectName    string
RoleName      string
GrantorName   string
PrivilegeName string
DbName        string
}
```
PyMilvus's implementation (and signatures, names) of such methods was taken as an inspiration here. 
Thanks!
=> enhance: Add ListGrants and ListGrant RBAC methods

entity/columns_vector_gen.go
Preventing sliced column with dim=0
=> fix: Set dimension for Vector column `Slice` method

entity/columns_array.go, entity/columns_array_gen.go, entity/columns_json.go, entity/columns_scalar_gen.go, entity/columns_sparse.go, entity/columns_varchar.go, entity/columns_vector_gen.go
Fix slice may panic with out of bound error when last batch is not sufficent for batch size in query iterator
=> fix: Set Slice start to Len if out-of-bound

client/results.go, entity/columns.go, entity/columns_array.go, entity/columns_array_gen.go, entity/columns_json.go, entity/columns_scalar_gen.go, entity/columns_sparse.go, entity/columns_varchar.go, entity/columns_vector_gen.go
=> fix: Make FP16 & BF16 column use correct byte len when parsing

test/testcases/insert_test.go, test/testcases/upsert_test.go
Insert/Upsert behavior changes for milvus master branch. This PR updates some error message and error check for upsert with PKs when autoID=true.
=> enhance: Sync autoID insert/upsert test cases

client/client.go, client/rbac.go, client/rbac_test.go
The latest version of the SDK doesn't pass the actual privilege that is granted during a Grant() call. This causes the Grant call to fail in any situation. 
This PR fixes this issue by extending the method signature to take a `privilege` parameter, similarly to how the Python SDK does. This was an easy fix because the protobuf structs already had the field in place, so the SDK only needs to use that correct field in the API call.
=> fix broken Grant() call

client/insert.go, entity/columns_json.go, test/testcases/insert_test.go, test/testcases/search_test.go
Related to #806
Previously all columns not appeared in schema definition are treated as dynamic columns. This PR allows specifying one JSON column to be the THE dynamic column data.
=> enhance: Allow explicit dynamic JSON column as insert data

.github/workflows/test-ci.yaml, test/testcases/groupby_search_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go
- update cases
- update ci server image to 2.4
=> test: Update ci server image to 2.4 and update cases

entity/rows.go, entity/rows_test.go
Cherry-pick from master
pr: #823 
Related to #818
=> enhance: [2.4] Support embedded struct field as Row input (#823)

client/data.go, client/results.go, client/results_test.go, test/testcases/groupby_search_test.go
=> feat: [2.4] Support unmarshal resultset into orm receiver (#827)

client/client.go
Current implementation is buggy and not ready for prod. Hide it until fixed.
=> enhance: [2.4] Hide buggy search iterator interface

client/data.go, client/options.go, client/options_test.go, test/common/response_check.go, test/common/utils.go, test/testcases/delete_test.go, test/testcases/groupby_search_test.go, test/testcases/index_test.go, test/testcases/query_test.go, test/testcases/search_test.go
This PR fix the failing e2e cases for master branch
- Error message changes for expression validation
- Skip timeout & unexpected message change
- Use current consistency level param to avoid iterator issues
=> fix: Update error message and other behavior change

client/client.go, client/client_mock_test.go, client/rbac.go, entity/rbac.go, go.mod, go.sum, mocks/MilvusServiceServer.go
cherry-pick from master: https://github.com/milvus-io/milvus-sdk-go/pull/845, https://github.com/milvus-io/milvus-sdk-go/pull/847
issue: https://github.com/milvus-io/milvus/issues/37031
=> enhance: [2.4] RBAC privielge group and grant v2 api

entity/index.go, entity/index_test.go
issue: https://github.com/milvus-io/milvus/issues/35464
Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit a1f6fffa86d5c75873bbe0a828bd68cc0dd37c38)
=> feat: [2.4]add page retain order for range search

client/client.go, client/rbac.go
cherry-pick from master: https://github.com/milvus-io/milvus-sdk-go/pull/852
issue: https://github.com/milvus-io/milvus/issues/37031
=> fix: [2.4] optional db for grant/revoke v2

client/ann_request.go, client/data.go, client/options.go
issue: https://github.com/milvus-io/milvus/issues/37360
=> enhance: support hints param

client/data.go, client/results.go, go.mod, go.sum, test/testcases/load_release_test.go
=> enhance: [2.4] support recall in SearchResult
