CHANGELOG.md, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Add 2 metric types and fix search bug

CHANGELOG.md, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go, test/client_test.go
=> Put id_array in insert return parameter

CHANGELOG.md, milvus/MilvusClient.go
=> Add annoy index type

README.md
=> Add 0.2.0 tags in README.md

CHANGELOG.md, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Search won't return status when return nq = 0

README.md
=> Add 0.3.0 README.md

CHANGELOG.md, milvus/ClientProxy.go, milvus/MilvusClient.go, milvus/MilvusGrpcClient.go, milvus/grpc/gen/milvus.pb.go, milvus/grpc/milvus.proto, test/client_test.go
=> Fix interface for milvus-0.9.0

test/client_test.go
=> Add GetEntitiesByID unittest

CHANGELOG.md, examples/MilvusClientExample.go, milvus/ClientProxy.go
=> Filtering id = -1 result when total count < topk

CHANGELOG.md, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go, test/client_test.go
=> Rename sdk interfaces

CHANGELOG.md, README.md, milvus/ClientProxy.go, milvus/MilvusClient.go, milvus/MilvusGrpcClient.go
=> Remove SearchByID

CHANGELOG.md, README.md, milvus/ClientProxy.go
=> merge 0.4.1

CHANGELOG.md, README.md, milvus/ClientProxy.go
=> Fix sever version check for milvus-0.10.0

CHANGELOG.md, milvus/ClientProxy.go
=> ListPartitions returns wrong result

README.md, test/client_test.go
=> fix test cases for 0.10.1

README.md
=> Fix Readme.md 0.4.4

README.md
=> fix doc for milvus-0.11.0

.gitignore, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Add example

.gitignore, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Add example (#53)

.gitignore, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Change FieldName DataType to Name type

examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Change FieldName to Name in InsertParam

examples/MilvusClientExample.go
=> Change segment_row_count to segment_row_limit

examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Support RHNSW-pq/sq in go-sdk

milvus/ClientProxy.go
=> Fix GetEntityByID return ID

CHANGELOG.md, milvus/ClientProxy.go
=> Insert binary vector failed

CHANGELOG.md, milvus/ClientProxy.go, milvus/MilvusClient.go, milvus/MilvusGrpcClient.go
=> Function HasPartition is not found in go-sdk

CHANGELOG.md, examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go, milvus/Params.go
=> Add params structure to process complex json string

CHANGELOG.md, examples/MilvusClientExample.go, milvus/ClientProxy.go
=> Change the initialization of go sdk client

examples/MilvusClientExample.go, milvus/ClientProxy.go, milvus/MilvusClient.go
=> search 函数增加fields参数

README.md
=> Fix readme for 0.4.5

README.md
=> Fix readme of milvus version-0.10.6 and sdk version-0.4.6

README.md
=> Fix 1.0 readme

README.md
=> Change corresponding version in readme

README.md, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Update version check for 1.1.x

README.md
=> Change 1.0.0 to 1.0.1 in readme

examples/MilvusClientExample.go, go.mod, go.sum, milvus/ClientProxy.go, milvus/MilvusClient.go
=> Fix grpc version

.golangci.yml, Makefile, client/client.go, client/client_grpc.go, entity/collection.go, entity/schema.go, go.mod, go.sum, tests/client_collection_test.go, tests/client_partition_test.go
Add collection & partition api wrapper
Add golangci-lint config
=> Add collection partition api wrapper

.gitignore, client/client.go, client/client_grpc_dd.go, client/client_grpc_dm.go, entity/gen/gen.go, entity/index.go, entity/schema.go, entity/segment.go, tests/client_index_test.go
Add index related api wrapper
Add  raw Index model(Generic Index)
Fix some lint issue
=> Add raw index api

client/client_grpc_dm.go
=> Fix flush async wait logic

client/client_grpc_dd.go, client/client_grpc_dd_test.go
Add context done global ut logic
Fix sync load logic
See also: #114 
=> Add ctx done global ut

client/client.go, client/client_grpc_dd.go, client/client_grpc_dd_test.go, client/client_grpc_dm_test.go, client/client_mock_test.go
Add client unit tests
Related #114 
=> Add client unit tests

Makefile, client/client_mock_test.go, scripts/run_go_unittest.sh
[skip-ci] add unit test make file entry
=> Add unit test make entry

.github/workflows/main.yml
Add github action for unittest
=> Add unit test action

client/client.go, client/client_grpc_dd.go, client/client_grpc_dd_test.go, client/client_grpc_dm_test.go, client/client_mock_test.go, tests/client_collection_test.go, tests/client_index_test.go
Add partition load & release api
Add related unit test cases
Fix some lint issue
=> Add partition load/release

client/client_grpc_dd_test.go
Add unit test case for create collection
=> Add case for create collection

.github/mergify.yml, .github/workflows/main.yml
=> Add mergify config yml

README.md
Add license badge
Add mergify badge
=> Add mergify badge

client/client.go, client/client_grpc_dd.go, client/client_grpc_dd_test.go, client/client_mock_test.go
Unify client parameter to pointer
=> Unify client param signature

examples/README.md, examples/basic/basic.go
=> Add basic example and examples menu

client/client_grpc_dd.go, client/client_grpc_dd_test.go, client/client_grpc_dm.go, client/client_grpc_dm_test.go, client/errors.go
Add collection check
Related #133 
=> Add collection check

client/client_grpc_dd_test.go
Add CreateIndex sync test case
Related issue: #138 
=> Add CreateIndex sync test case

client/client_grpc_dd_test.go
Add ut test case for testing auto merge
=> Add ut test case

client/client_grpc_data.go, client/client_grpc_data_test.go
Add param check for `Search` API
Fix: #133 
=> Add param check for Search api

examples/README.md, examples/calcdistance/calc_distance.go
Add CalcDistance example and related README
Fix: #125 
=> Add CalcDistance example

README.md
=> Fix readme content

entity/rows.go, entity/rows_test.go
Add Row interface
Add ParseSchema method
Related issue: #161 
=> Add rows parse

client/client_grpc_row.go, client/client_grpc_row_test.go
Add SearchResult to Row util functions
Related issue: #161 
=> Add SearchResult to Rows

client/client_grpc_data.go, client/client_grpc_data_test.go
Split Search request according to row size
Fix issue: #167 
=> Split Search request according to row size

client/client.go, client/client_grpc_collection_test.go, client/client_grpc_row.go, client/client_grpc_row_test.go, client/client_test.go
Add CreateCollectionByRow
Add Unit test for row based feature functions
Related issue: #161 
=> Add CreateCollectionByRow

docs/README.md, docs/create_collection.md, docs/create_index.md, docs/create_partition.md, docs/describe_collection.md, docs/describe_index.md, docs/drop_collection.md, docs/drop_index.md, docs/drop_partition.md, docs/flush.md, docs/get_index_build_progress.md, docs/has_partition.md, docs/insert.md, docs/list_collections.md, docs/load_collection.md, docs/load_partitions.md, docs/new_client.md, docs/release_collection.md, docs/release_partitions.md, docs/search.md, docs/show_partitions.md
Add API document markdown
Fix #126 
=> Add API documents markdown

docs/README.md, docs/create_collection.md, docs/create_index.md, docs/create_partition.md, docs/describe_collection.md, docs/describe_index.md, docs/drop_collection.md, docs/drop_index.md, docs/drop_partition.md, docs/flush.md, docs/get_index_build_progress.md, docs/has_partition.md, docs/insert.md, docs/list_collections.md, docs/load_collection.md, docs/load_partitions.md, docs/new_client.md, docs/release_collection.md, docs/release_partitions.md, docs/search.md, docs/show_partitions.md
API reference revision phase one
=> [skip ci] revise api reference

.github/workflows/main.yml
Add action for master pull action
Related #185 
=> Fix master coverage not triggered

.github/mergify.yml
=> Update mergify, compulsory related issue

docs/index_limitations.md
Related issue: #190 
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
=> [skip ci] Create Index Parameter Range Template

client/client_grpc_collection.go, client/client_grpc_collection_test.go, client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_grpc_partition.go, client/client_grpc_partition_test.go
Respect deadline in sync wait
Fix: #192 
=> Respect context deadline when doing sync wait

CONTRIBUTING.md
Fix #197 
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
=> [skip ci] Update Go SDK contributing guide

.github/mergify.yml
=> [skip ci] PR with kind/improvement label can bypass need-issue rule

docs/create_collection.md, docs/create_index.md, docs/create_partition.md, docs/describe_collection.md, docs/describe_index.md, docs/drop_collection.md, docs/drop_index.md, docs/drop_partition.md, docs/flush.md, docs/get_index_build_progress.md, docs/has_partition.md, docs/index_limitations.md, docs/insert.md, docs/list_collections.md, docs/load_collection.md, docs/load_partitions.md, docs/new_client.md, docs/release_collection.md, docs/release_partitions.md, docs/search.md, docs/show_partitions.md
Related issue: #191 
Signed-off-by: LocoRichard <lichen.wang@zilliz.com>
=> [skip ci] Modify API reference

client/client.go, client/client_grpc_data.go, client/client_grpc_partition.go, client/client_grpc_partition_test.go, entity/collection.go, examples/basic/basic.go, tests/testutil/utils.go
run the examples error  for the array without check length 
Fix #236
=> Fix spell error and  check empty array

client/client_grpc_collection.go, client/client_grpc_collection_test.go
=> Return error when CreateCollection response has error

client/client.go, client/client_grpc_alias.go, client/client_grpc_alias_test.go, client/client_mock_test.go
=> Add Alias related API

client/client.go, client/client_grpc_control.go, client/client_grpc_control_test.go, client/client_mock_test.go, client/client_test.go, entity/compaction.go, internal/utils/tso/tso.go, internal/utils/tso/tso_test.go
=> Add compaction API

client/client.go, client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_mock_test.go, client/client_test.go
=> Add Delete API

client/client_grpc_collection.go, client/client_grpc_collection_test.go
=> Set loaded flag in ListCollections

client/client_grpc_data.go
Fix #231 
/kind bug
Co-authored-by: mengzeliang <276212324@qq.com>
=> Fix search scores index searching multiple vectors

client/client_grpc_collection.go, client/client_grpc_partition.go, client/client_grpc_partition_test.go
=> Make ListCollections and ShowParitions work with unloaded ones

client/client_grpc_collection_test.go, client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_mock_test.go, entity/rows.go, entity/schema.go, examples/basic/basic.go, examples/calcdistance/calc_distance.go, examples/index/index.go, examples/insert/insert.go, tests/client_collection_test.go, tests/testutil/utils.go, tests/util.go
Set "dim" to const value for reference
Related #252
=> Use const value for vector field dimension key

client/client_grpc_index_test.go
Add unit tests for index related APIs
=> Add unit tests for index related apis

README.md
- Update readme Version recommendation
- Remove Hacktoberfest banner
=> Fix README.md for v2.0.0 and remove banner

client/client.go, client/client_grpc_collection.go, client/client_grpc_collection_test.go, client/client_grpc_options.go, client/client_grpc_options_test.go, client/client_test.go, entity/schema.go, entity/schema_test.go
Related issue #263
Add ConsistencyLevel in entity
Add CreateCollection options and ConsistencyLevelOption
/kind feature
=> Add ConsistencyLevel support in CreateCollection

client/client_grpc_collection.go, client/client_grpc_control.go, client/client_grpc_data.go, client/client_grpc_partition.go, client/client_grpc_row.go
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>
=> Remove duplicate checks

milvus/ClientProxy.go, milvus/MilvusClient.go
Signed-off-by: litongxue <litonglitong@hotmail.com>
=> 1.x supoort modify grpc client option

client/client.go, client/client_grpc_collection.go, client/client_grpc_collection_test.go, client/client_grpc_options.go, client/client_grpc_options_test.go, client/client_mock_test.go
Add ReplicaNumber option in LoadCollection
Related to #272 
Signed-off-by: Letian Jiang <letian.jiang@outlook.com>
=> Add ReplicaNumber option in LoadCollection

client/client.go, client/client_grpc_collection.go, client/client_grpc_collection_test.go, client/client_grpc_control_test.go, client/client_mock_test.go, entity/collection.go
Add GetReplicas API for supporting memory replica
Close #272 
Signed-off-by: Letian Jiang <letian-jiang@zilliz.com>
=> Add GetReplicas API for supporting memory replica

client/client.go, client/client_grpc_authentication.go, client/client_grpc_authentication_test.go, client/client_grpc_collection.go, client/client_grpc_options.go, client/client_mock_test.go, client/interceptor.go, client/interceptor_test.go, examples/auth/auth.go, internal/utils/crypto/crypto.go
Fix #284
Signed-off-by: Letian Jiang <letian-jiang@zilliz.com>
=> Support login with username and password

examples/query/query.go
Signed-off-by: Letian Jiang <letian.jiang@zilliz.com>
=> Add example for searching with specified consistency level

.github/mergify.yml, .github/workflows/golangci-lint.yml, client/client_grpc_partition.go
=> Add golangci-lint workflow for PR and mergify rules

client/client_grpc_data.go, client/client_grpc_data_test.go, entity/columns.go
=> Fix PlaceHolderValue type is wrong when searching binary vector

README.md
=> Update README.md for v2.1.0

tests/client_collection_test.go, tests/client_dm_test.go, tests/client_index_test.go, tests/collection_test.go, tests/main_test.go, tests/util.go
Signed-off-by: Letian Jiang <letian.jiang@zilliz.com>
=> Fix e2e test

client/client_grpc_data.go, examples/hello_milvus/hello_milvus.go, examples/varchar/varchar_pk.go
Signed-off-by: Letian Jiang <letian.jiang@zilliz.com>
=> Fix delete with varchar primary key

client/client.go, client/client_grpc_collection.go, client/client_test.go, examples/auth/auth.go
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>
=> To compatiable with auth interceptor for Grpc opts

client/ctx.go, client/ctx_test.go
add interfaces to pass tracing variables:
- log level
- client trace id
ISSUE: #307
=> add client tracing interfaces

client/client_grpc_collection.go
fix #312 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>
=> Fix bug: collection cache missed caused by empty collectionName

client/client_grpc_index.go, client/client_grpc_index_test.go
flush segment before create index
fix #277
Signed-off-by: wgcn <1026688210@qq.com>
=> flush segment before create index

client/client.go
See also #305 
Signed-off-by: wayblink anyang.wang@zilliz.com
=> Expose GetPersistentSegmentInfo Interface

client/client.go, client/rate_limit_interceptor.go, client/rate_limit_interceptor_test.go
Resolves #321 
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>
=> Retry on rate limit

client/client_grpc_data.go
=> Set nq param in SearchRequest

.github/workflows/nightly_ci.yml, ci/docker/milvus/docker-compose.yml, ci/scripts/docker_image_find_tag.sh, tests/e2e/connect_test.go
=> Add nightly ci framework

client/client.go, client/client_test.go
/kind improvment
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>
=> Add a NewDefaultGrpcClientWithURI API

.github/workflows/test-ci.yaml, ci/milvus-operator/milvus-cluster.yaml, ci/milvus-operator/milvus-standalone.yaml, ci/scripts/export_log_k8s_for_operator.sh, test/testcases/insert_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add ci test workflows
- Add milvus operator deploy yaml
- Add operator pod exporter
- Update skip case
=> Add ci test workflow and operator log exporter and default milvus yaml

.github/mergify.yml, .github/workflows/test-ci.yaml
=> Add ci test in mergify

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/connect_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/main_test.go
- Add create collection test case
- Update error check
- Add some utils func
issue: #335 
=> Add collection cases and update check err func

client/client_grpc_index.go, client/client_grpc_index_test.go, examples/hello_milvus/hello_milvus.go
=> Fix CreateIndex check building progress behavior

.github/mergify.yml
=> Fix mergify rule for e2e

client/client.go, client/client_grpc_collection_test.go, client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_grpc_options.go, client/client_grpc_options_test.go
=> Add query and pagination

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/connect_test.go, test/testcases/insert_test.go, test/testcases/main_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add insert cases
- Add connect cases
- Update util func
issue: #215 
=> Add connect and insert cases

.github/mergify.yml
=> Fix mergify rules for e2e case only

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/connect_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/main_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add index cases
- Add some utils func
- Add some test help func
=> Add index cases

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/main_test.go, test/testcases/query_test.go
- Add query test cases
issue: #215 
=> Add query test cases

test/base/milvus_client.go, test/testcases/collection_test.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/main_test.go, test/testcases/query_test.go
- Add flush and delete cases
issue: #335 
=> Add flush and delete cases

.github/workflows/test-ci.yaml, test/base/milvus_client.go, test/common/response_check.go, test/testcases/collection_test.go, test/testcases/configure_test.go, test/testcases/connect_test.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add collection load release cases
- Add partition load release cases
- Add test case L0 L3 build tag
issue: #335 
=> Add collection partition load release case and L0 L3 tag

test/testcases/index_test.go
=> Add re-create index case

test/testcases/search_test.go
- Skip some search cases for knowhere 2.0 error changed
Signed-off-by: ThreadDao yufen.zong@zilliz.com
=> Skip some search cases for knowhere 2.0 error changed

client/client_grpc_collection.go, client/client_grpc_data.go, client/client_grpc_options.go
=> add `WithCollectionProperties` option and support the back field name for `PKs2Expr`

test/base/milvus_client.go, test/common/utils.go, test/testcases/compact_test.go, test/testcases/configure_test.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go, test/testcases/query_test.go, test/testcases/search_test.go
=> Add compact test cases

client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_grpc_options.go, client/client_grpc_options_test.go
related: #407 https://github.com/milvus-io/milvus/issues/21836
Signed-off-by: aoiasd [zhicheng.yue@zilliz.com](mailto:zhicheng.yue@zilliz.com)
=> add IgnoreGrowing option

client/client_grpc_collection_test.go, client/client_mock_test.go
=> Refactor collection list,create unit test

entity/bulkinsert.go
related:#393
Signed-off-by: wayblink <anyang.wang@zilliz.com>
=> Support get bulk insert progress

client/client_grpc_collection.go, client/client_grpc_collection_test.go, test/common/utils.go
=> Set default consistency level to Bounded

client/client_grpc_data.go, client/client_grpc_data_test.go, client/client_grpc_options.go, client/client_grpc_options_test.go
related: https://github.com/milvus-io/milvus-sdk-go/issues/407 https://github.com/milvus-io/milvus/issues/21836
Signed-off-by: aoiasd [zhicheng.yue@zilliz.com](mailto:zhicheng.yue@zilliz.com)
=> add IgnoreGrowing option (#406)

client/client.go, client/client_mock_test.go, client/collection.go, client/collection_test.go, entity/collection_attr.go, entity/collection_attr_test.go, go.mod, go.sum, mocks/MilvusServiceServer.go
=> Add AlterCollection API

docs/create_collection.md, entity/collection.go, examples/basic/basic.go, examples/calcdistance/calc_distance.go, examples/hello_milvus/hello_milvus.go, examples/index/index.go, examples/insert/insert.go, examples/query/query.go, examples/tls/tls.go, examples/varchar/varchar_pk.go, test/testcases/search_test.go
=> Use Milvus default shard number

docs/create_collection.md, entity/collection.go, examples/basic/basic.go, examples/calcdistance/calc_distance.go, examples/hello_milvus/hello_milvus.go, examples/index/index.go, examples/insert/insert.go, examples/query/query.go, examples/tls/tls.go, examples/varchar/varchar_pk.go
=> [2.2.x] Use Milvus default shard number

entity/columns_json.go, entity/columns_json_test.go, entity/schema.go
See also #432 
Related to https://github.com/milvus-io/milvus/issues/23389
=> Add JSON data type

entity/columns.go
=> Support to search/query json

entity/columns.go
=> Fix vector field type check logic

entity/columns.go, entity/columns_test.go
See also https://github.com/milvus-io/milvus/issues/23850
=> [Cherry-Pick] Handle LongData returned when queryresult is empty (#450)

entity/collection_attr.go, entity/collection_attr_test.go, test/testcases/index_test.go, test/testcases/load_release_test.go, test/testcases/search_test.go
Related to https://github.com/milvus-io/milvus/issues/23993
=> Add AutoCompactionEnabled collection attribute

entity/index.go
Related to https://github.com/milvus-io/milvus/pull/23350
=> Add COSINE metric type

client/client_mock_test.go, client/meta_cache.go, client/row.go, client/row_test.go, entity/rows.go, entity/rows_test.go
=> Adapt dynamic field and support insert by rows

entity/schema.go, entity/schema_test.go
See also milvus-io/milvus#23553
=> Add PartitionKey definition for schema

entity/rows.go, entity/rows_test.go, examples/dynamic_schema/dynamic_schema.go
=> [2.2.x] Support row interface with map[string]any

client/collection.go, client/options.go, client/options_test.go
See also milvus-io/milvus#24402
=> [2.2.x] Add logical partition num option for create collection

entity/rows.go, entity/rows_test.go
=> Ignore AutoID pk when converting rows to columns

entity/rows.go, entity/rows_test.go
=> Ignore AutoID pk when converting rows to columns (#470)

client/config.go, client/config_test.go, client/interceptor.go, client/interceptor_test.go
=> [2.2.x] Support API token config

client/client.go, client/row.go, entity/rows.go
=> Add InsertRows API and mark InsertByRows deprecated

client/data.go, entity/schema.go, examples/dynamic_schema/dynamic_schema.go
Handles wildcard outputFields
- Use response outputFields if provided
- Expand wildcard client-side
=> [2.2.x] Handle wildcard and outputFields

examples/query/query.go
=> [2.2.x] Update query example code

client/collection.go, client/collection_test.go, test/common/utils.go
=> [2.2.x] Change collection default consistency level

client/client.go, client/insert.go, client/options.go
=> Update to support milvus-backup

client/collection.go, client/collection_test.go
Move collection duplication check to server side
=> Remove HasCollection check for create collection

client/interceptor.go, client/interceptor_test.go
=> Fix api token format

client/grpc_client.go, go.mod, go.sum
=> Bump milvus-proto v2.2.10 SDK version v2.2.4

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/testcases/connect_test.go, test/testcases/database_test.go, test/testcases/delete_test.go, test/testcases/main_test.go
- Add database cases
- Fix delete case
issue: #368
=> Add database cases and fix delete cases

client/client.go, client/collection.go, client/collection_test.go, client/options.go, client/options_test.go, entity/collection.go, entity/index.go, test/testcases/database_test.go
Add `NewCollection` as high level api to create collection with default setup
=> Add NewCollection high level API

client/client.go, client/data.go, client/data_test.go, client/options.go
=> Add highlevel API `Get`

client/collection.go, client/options.go
=> Add PK max length option

client/collection.go, client/options.go
=> Enable dynamic schema for high-level newcollection by default

client/data.go, client/data_test.go, client/options.go, client/options_test.go
milvus issue: https://github.com/milvus-io/milvus/issues/25151
=> Add forTuning option

client/collection.go, client/options.go
=> Add back CollectionProperty option

.github/workflows/nightly_ci.yml
=> Fix nightly ci action

.github/mergify.yml, .github/workflows/nightly_ci.yml
=> Fix workflow syntax & mergify condition

client/client.go, client/collection.go, client/collection_test.go, client/config.go, client/data.go, client/data_test.go, client/database.go, client/errors.go, client/grpc_client.go, client/interceptor.go, client/interceptor_test.go, client/options.go, client/options_test.go, client/partition.go, client/partition_test.go, client/results.go, entity/collection.go
CP change from #493 #496 #502 #505 #506 #508 #509
=> Sync v2.2.x change to master

entity/genidx/genidx.go, entity/index.go, entity/indexes_search_param_gen.go
=> Make SearchParams extensible

client/config.go, client/config_test.go
=> Auto fill 443 port for https schema url

entity/index.go, entity/index_test.go
Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
https://github.com/milvus-io/milvus/issues/21655
=> Support range search

OWNERS
=> Add yah01 as OWNER

examples/insert/insert.go
chang code:
`Description:    "this is the example collection for inser and search"`
to:
`Description:    "this is the example collection for insert and search"`
=> modify the description

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/common/utils_client.go, test/testcases/collection_test.go, test/testcases/configure_test.go, test/testcases/connect_test.go, test/testcases/database_test.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go, test/testcases/query_test.go, test/testcases/resource_group_test.go, test/testcases/search_test.go
- add json test cases, include create collection, insert, index, query, search
- add dynamic field test cases, included create, insert, index, query, search
- update some utils func and main test help func
=> Add json field and dynamic field test cases

client/client.go, client/config.go, client/config_test.go, client/rate_limit_interceptor.go, client/rate_limit_interceptor_test.go, client/row.go, entity/rows.go
=> Sync InsertRows and config related PR to master

.github/mergify.yml
=> Add pass rule for example code change

client/insert.go
=> Remove set default partition name logic

.github/mergify.yml
=> Fix mergify example code rule file path

examples/partitionkey/main.go
=> Add partition key example

test/testcases/resource_group_test.go
=> Fix resource group L3 case code

client/insert.go, examples/partitionkey/main.go
=> Cherry pick partition key fix and example

ci/milvus-operator/milvus-nightly.yaml
=> Add milvus-nightly.yaml for v2.2.x branch

test/common/utils.go, test/testcases/partition_key_test.go
- Add partition key test cases
=> Add partition key cases

entity/genidx/genidx.go, entity/index.go, entity/indexes_gen.go, entity/indexes_gen_test.go, entity/indexes_search_param_gen.go, entity/indexes_search_param_gen_test.go
Add `GPUIvfFlat` and `GPUIvfPQ` index support
=> Support GPU index type and search param

.github/workflows/test-ci.yaml, test/base/milvus_client.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/delete_test.go, test/testcases/highlevel_test.go, test/testcases/index_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go, test/testcases/partition_key_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- add highlevel api cases
- update fun Query to QueryByPks in milvus_client.go
- add generate column func and update utils
=> Add highlevel cases and update utils func

.github/workflows/nightly_ci.yml
Change job name so we could distinguish job for each branch
=> Change nightly job name for branches

entity/genidx/genidx.go, entity/index.go, entity/indexes_gen.go, entity/indexes_gen_test.go, entity/indexes_search_param_gen.go, entity/indexes_search_param_gen_test.go
See also milvus-io/milvus#26099
=> Support SCANN index type

client/data.go, client/index.go, entity/index.go, entity/index_scalar.go, examples/index/index.go, test/testcases/index_test.go
=> [Cherry-Pick] Support scalar index (#498)

client/index.go
=> Remove the field name check of the drop index api

entity/columns_json.go, entity/columns_json_test.go
=> Support append struct/map to json column

ci/milvus-operator/milvus-nightly.yaml, test/testcases/resource_group_test.go
- [cherry-pick] Fix 2.2 nightly
=> Update L3 cases and nightly qn replicas (#547)

test/base/milvus_client.go, test/common/response_check.go, test/common/utils.go, test/common/utils_client.go, test/testcases/collection_test.go, test/testcases/connect_test.go, test/testcases/database_test.go, test/testcases/delete_test.go, test/testcases/flush_test.go, test/testcases/highlevel_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go, test/testcases/partition_key_test.go, test/testcases/query_test.go, test/testcases/resource_group_test.go, test/testcases/search_test.go
- add json and dynamic field cases
- add partition key cases
- add highlevel API cases
=> Add json dynamic filed, partition key, highlevel test cases

test/testcases/highlevel_test.go, test/testcases/index_test.go
=> Add back testcases skipped for issue 555

client/grpc_client.go
=> Bump SDK version to v2.2.8

test/testcases/index_test.go, test/testcases/search_test.go
- master branch added `SUBSTRUCTURE` & `SUPERSTRUCTURE`
- collection not existed add database name in error message
/kind bug
=> Fix master branch ci cases

client/client_mock_test.go, client/collection.go, client/collection_test.go, client/insert_test.go, client/partition_test.go, client/row_test.go, entity/schema.go, test/testcases/search_test.go
=> Use DescribeCollection for HasCollection impl

client/client.go, client/data_test.go, client/insert.go, test/base/milvus_client.go
relate: https://github.com/milvus-io/milvus-sdk-go/issues/577
=> add delete by expression method

entity/genidx/genidx.go, entity/indexes_gen.go, entity/indexes_gen_test.go
https://github.com/zilliztech/knowhere/issues/73
=> ScaNN support with_raw_data build option

test/testcases/resource_group_test.go
see also https://github.com/milvus-io/milvus-sdk-go/actions/runs/6226320255/job/16898611430
=> Fix nightly `TestTransferReplicaNotExistedCollection` case err msg

test/testcases/search_test.go
See also https://github.com/milvus-io/milvus-sdk-go/actions/runs/6252425920/job/16975679614
=> Fix nightly case `TestSearchInvalidExpr` error msg

client/alias_test.go, client/client_mock_test.go
=> Use mockery for Alias series API unittest

test/testcases/database_test.go
https://github.com/milvus-io/milvus-sdk-go/actions/runs/6499324811/job/17652453008
=> Fix `TestUsingDb` case error message

test/base/milvus_client.go, test/common/utils.go, test/testcases/delete_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add case for query count and expr
- Add case for delete expr
./kindimprovement
=> Add count and query test cases

test/common/utils.go, test/testcases/index_test.go, test/testcases/main_test.go, test/testcases/query_test.go, test/testcases/search_test.go
- Add cases for scann index
- Add case for range search
- Fix case
See also #594
=> Add case for scann index and range search

test/testcases/database_test.go
=> Fix L0 testcase TestDropDb error msg

client/client_mock_test.go, common/common.go, go.mod, go.sum, mocks/MilvusServiceServer.go
=> Bump SDK Version & milvus-proto/go-api to v2.3.2

test/testcases/database_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/resource_group_test.go, test/testcases/upsert_test.go
Update cases due to error message change
( Fix cases failed in nightly)
=> Update cases due to error message change

test/testcases/collection_test.go, test/testcases/index_test.go
=> Fix case failed in nightly

test/testcases/query_test.go, test/testcases/search_test.go
Update search/query output field case for behavior changed
issue: https://github.com/milvus-io/milvus/issues/28465
=> Skip output invalid field case

test/testcases/search_test.go
the error message of search with invalid vectors change
=> Fix: case error msg change

.github/workflows/test-ci.yaml
Setup milvus image tag to 2.3 for v2.3.x branch
=> enhance: setup ci image to milvus 2.3

.github/mergify.yml, .github/workflows/test-ci.yaml
=> enhance: [cherry-pick] adjust workflow for merr & branches (#652)

test/testcases/index_test.go
the error message of index with invalid field or metric type
=> test: case error msg change

entity/collection_attr.go
This reverts commit 43226a3ea27a218698f5c13fe58cab73750633a6.
=> Reapply "feat: support enabling mmap for collection (#632)" (#635)

client/client_mock_test.go, client/data.go, client/data_test.go, client/options.go, client/results.go, examples/groupby/main.go, go.mod, go.sum, mocks/MilvusServiceServer.go
See also milvus-io/milvus#25324 milvus-io/milvus#28983
=> enhance: Support Search GroupBy feature

test/testcases/search_test.go
See also milvus-io/milvus#30623
=> fix: Use latest error message for range_filter and radius check

entity/rows.go, entity/rows_test.go
=> Fix: Adapt bf16/fp16 in row-based API

entity/index.go, entity/index_scalar.go, entity/index_scalar_test.go
=> fix: Allow specify scalar index type

.github/workflows/nightly_ci.yml, .github/workflows/test-ci.yaml, client/ann_request.go, test/testcases/groupby_search_test.go, test/testcases/index_test.go, test/testcases/search_test.go
- fix: cannot get latest amd54 image tag
- fix: NewANNSearchRequest miss expr param
- fix: case error mag
=> Fix: cannot find the latest amd image tag

client/collection.go, entity/collection.go
=> enhance: Add collection `Properties` field for describe collection

entity/columns_sparse.go
=> fix: Use corrent idx when converting SparseVector

client/data.go, client/data_test.go, client/results.go, examples/groupby/main.go
=> fix: Parse group by value for each rows of resultset

entity/rows.go
=> fix: Use correct index range for refect Slice method

client/client.go, client/client_mock_test.go, client/database.go, client/database_test.go, client/options.go, entity/collection_attr.go, entity/database.go, examples/database/database.go, go.mod, go.sum, mocks/MilvusServiceServer.go, test/base/milvus_client.go, test/testcases/database_test.go
issue: milvus-io/milvus#32707  milvus-io/milvus#30040
=> enhance: Add api for describe database and alter database

README.md
=> docs: add bump version 2.4.0 to readme

client/client.go, client/client_test.go, client/data.go, client/iterator.go, client/options.go, client/results.go, entity/columns.go, entity/columns_array.go, entity/columns_array_gen.go, entity/columns_json.go, entity/columns_scalar_gen.go, entity/columns_sparse.go, entity/columns_varchar.go, entity/columns_vector_gen.go, examples/iterator/main.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/upsert_test.go
Support query iterator interface in GoSDK
=> enhance: Support query iterator

client/iterator.go, test/testcases/index_test.go
=> fix: Use lower case "and" operator in query iterator

client/iterator.go
=> fix: Add parentheses for query iterator origin expr

client/iterator.go
=> fix: Check batch size when initializing iterator

client/iterator.go
=> fix: Check empty expr before compose iterator next batch

client/client.go, client/collection.go, client/options.go
Support specifiy check in-memory status when use `ListCollections`
=> enhance: Support InMemory option for ListCollection

client/client.go, client/insert.go
=> Support CDC

client/client.go, client/options.go, client/options_test.go, client/resource_group.go, client/resource_group_test.go, entity/resource_group.go, examples/resourcegroup/resourcegroup.go, test/testcases/resource_group_test.go
issue: https://github.com/milvus-io/milvus/issues/32282
- Add UpdateResourceGroups and modify AddResourceGroup api.
- Add example for add resource group declarative api.
=> enhance: add resource group declarative api

client/collection.go, client/collection_test.go
=> enhance: Remove the logic to set replica_number=1 by default

.github/workflows/nightly_ci.yml, .github/workflows/test-ci.yaml, test/testcases/index_test.go
=> test: add case to test inverted index on array field

client/collection_test.go, entity/collection_attr.go, entity/collection_attr_test.go
issue: https://github.com/milvus-io/milvus/issues/34332
=> feat: add support for partition key isolation property

entity/schema.go, entity/schema_test.go
See also milvus-io/milvus#32939
=> enhance: Support specifying field schema to be cluster key

client/client.go, client/client_test.go, client/iterator.go, client/iterator_option.go, client/results.go
Support search iterator with range search in Go SDK
=> enhance: Support search iterator in GoSDK

client/options.go
=> enhance: Add isL0,SkipDiskQuotaCheck option in Bulkinsert API

client/client.go, client/client_mock_test.go, client/client_test.go, client/rbac.go, client/rbac_test.go, entity/rbac.go, examples/rbac/main.go, go.mod, go.sum, mocks/MilvusServiceServer.go
=> enhance: Add BackupRBAC/RestoreRBAC API to enable rbac backup

client/client_mock_test.go, client/collection.go, client/collection_test.go, client/data.go, client/database.go, client/grpc_client.go, client/insert.go, client/iterator.go, client/meta_cache.go, client/options.go, client/options_test.go, client/row.go, go.mod, go.sum
=> fix: Make `MetaCache` field of GrpcClient

.github/workflows/nightly_ci.yml, test/testcases/index_test.go, test/testcases/load_release_test.go, test/testcases/main_test.go
test: updata v2.2 nightly to v2.4
test: update cases for mmap scalar index
=> test: updata v2.2 nightly to v2.4 and add mmap scalar index cases

test/testcases/groupby_search_test.go, test/testcases/index_test.go, test/testcases/load_release_test.go
1. pk field disable build BITMAP index
2. BITMAP and Hybrid indexes support mmap
3. IVF_SQ8 support group by
=> test: update test cases

entity/index.go, entity/index_test.go
issue: https://github.com/milvus-io/milvus/issues/35464
=> feat: add page retain order

entity/rows.go, entity/rows_test.go
=> enhance: Support embedded struct field as Row input

client/data.go, client/results.go, client/results_test.go, test/testcases/groupby_search_test.go
=> feat: Support unmarshal resultset into orm receiver

client/config.go, test/testcases/groupby_search_test.go
Cherry pick from master
pr: #832
Related to #831
=> enhance: [2.4] Set default max send recv size

client/rbac.go, examples/rbac/main.go
=> fix: RestoreRBAC pass wrong role info of user

client/config.go
=> enhance: Set default max send recv size

client/client.go, client/client_mock_test.go, client/rbac.go, go.mod, go.sum, mocks/MilvusServiceServer.go
issue: https://github.com/milvus-io/milvus/issues/37031
=> enhance: RBAC grant v2 API

go.mod, go.sum
Remove not compatible dependency from go.mod
=> fix: Remove uncompatible dep

client/client.go, client/rbac.go
issue: https://github.com/milvus-io/milvus/issues/37031
=> fix: optional db for grant/revoke v2

client/data.go, client/results.go, go.mod, go.sum
=> enhance: support recall in SearchResult

.github/workflows/test-ci.yaml, test/common/response_check.go, test/common/utils.go, test/testcases/collection_test.go, test/testcases/configure_test.go, test/testcases/groupby_search_test.go, test/testcases/index_test.go, test/testcases/insert_test.go, test/testcases/load_release_test.go, test/testcases/query_test.go, test/testcases/resource_group_test.go, test/testcases/search_test.go
- fix print without linebreak results in unknown, see issue https://github.com/gotestyourself/gotestsum/issues/205
=> test: fix print without linebreak results in unknown
